# Generated by Django 4.1.5 on 2023-01-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='unit',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
